apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vmya
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0010-tenant/tkwch-fix-0075-0010-app/devfile-sample-vmya@sha256:582fffaf80fb3c6aaa99f4fd21ff444bec22e29eeba806ca9f01b63303787790
        name: my-nodejs
        resources: {}
status: {}
